### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Warships_v0)
add_subdirectory(Warships_v0Content)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Warships_v0plugin
    Warships_v0Contentplugin
    QtQuickDesignerComponents)